// Fluent System Icons (MIT, microsoft/fluentui-system-icons) — the fallback
// table, trimmed to what the product asks for.
//
// The design system ships 266 of these, generated by fig_materialize. Three are
// referenced; the other 263 were 189 kB of glyph data in the shared bundle of
// every route, including the pages that render nothing but a not-built notice.
// The full table lives in `Design System/assets/icons/` in the design project —
// to use another glyph, copy its entry across by name. A name with no entry is
// not an error: `Icon` renders an empty box of the right size.
//
// The design system ships this table as a script that assigns onto `window`.
// Under SSR there is no window at module scope, so it is a plain ESM export
// here and glyphs.ts does the merging — same table, same names.
export default {
  "ArrowUpSize12ThemeRegular": { viewBox: "0 0 12 12", body: "<path d=\"M 4 9 C 4.276 9 4.5 8.776 4.5 8.5 L 4.5 1.707 L 7.146 4.354 C 7.342 4.549 7.658 4.549 7.854 4.354 C 8.049 4.158 8.049 3.842 7.854 3.646 L 4.354 0.146 C 4.158 -0.049 3.842 -0.049 3.646 0.146 L 0.146 3.646 C -0.049 3.842 -0.049 4.158 0.146 4.354 C 0.342 4.549 0.658 4.549 0.854 4.354 L 3.5 1.707 L 3.5 8.5 C 3.5 8.776 3.724 9 4 9 Z\" fill=\"currentColor\" fill-rule=\"evenodd\" transform=\"matrix(1 0 0 1 2 1.500)\"/>" },
  "ArrowUpSize16ThemeRegular": { viewBox: "0 0 16 16", body: "<path d=\"M 4.5 11.5 C 4.5 11.776 4.724 12 5 12 C 5.276 12 5.5 11.776 5.5 11.5 L 5.5 1.803 L 9.128 5.834 C 9.313 6.04 9.629 6.056 9.834 5.872 C 10.04 5.687 10.056 5.371 9.872 5.166 L 5.372 0.166 C 5.277 0.06 5.142 0 5 0 C 4.858 0 4.723 0.06 4.628 0.166 L 0.128 5.166 C -0.056 5.371 -0.04 5.687 0.166 5.872 C 0.371 6.056 0.687 6.04 0.872 5.834 L 4.5 1.803 L 4.5 11.5 Z\" fill=\"currentColor\" fill-rule=\"evenodd\" transform=\"matrix(1 0 0 1 3 2)\"/>" },
  "DismissSize16ThemeRegular": { viewBox: "0 0 16 16", body: "<path d=\"M 0.089 0.216 L 0.146 0.146 C 0.32 -0.027 0.589 -0.046 0.784 0.089 L 0.854 0.146 L 5.5 4.793 L 10.146 0.146 C 10.342 -0.049 10.658 -0.049 10.854 0.146 C 11.049 0.342 11.049 0.658 10.854 0.854 L 6.207 5.5 L 10.854 10.146 C 11.027 10.32 11.046 10.589 10.911 10.784 L 10.854 10.854 C 10.68 11.027 10.411 11.046 10.216 10.911 L 10.146 10.854 L 5.5 6.207 L 0.854 10.854 C 0.658 11.049 0.342 11.049 0.146 10.854 C -0.049 10.658 -0.049 10.342 0.146 10.146 L 4.793 5.5 L 0.146 0.854 C -0.027 0.68 -0.046 0.411 0.089 0.216 L 0.146 0.146 L 0.089 0.216 Z\" fill=\"currentColor\" fill-rule=\"evenodd\" transform=\"matrix(1 0 0 1 2.500 2.500)\"/>" },
}
